version: "3.8"

services:
  gophish:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gophish-pros      
    ports:
      - "3333:3333"      
      - "8080:8080"      
    depends_on:
      - mysql
    networks:
      - default

  mysql:
    image: mysql:8.3
    container_name: gophish-db
    command: mysqld --sql_mode="ALLOW_INVALID_DATES,NO_ZERO_DATE"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=gophish
      - MYSQL_USER=gophish_user
      - MYSQL_PASSWORD=gophish_password
      - MYSQL_ALLOW_ZERO_DATE=true
      - MYSQL_TCP_PORT=3306    
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql      

volumes:  
  mysql_data:
